"heroes"
{
	"strength"
{
		"1"
{
			"name" "npc_dota_hero_axe"
			"label" "axe"
		}
		"2"
{
			"name" "npc_dota_hero_sven"
			"label" "sven"
		}
		"3"
{
			"name" "npc_dota_hero_dragon_knight"
			"label" "dragon_knight"
		}
		"4"
{
			"name" "npc_dota_hero_sand_king"
			"label" "sand_king"
		}
		"5"
{
			"name" "npc_dota_hero_huskar"
			"label" "huskar"
		}
	}
	"agility"
{
		"1"
{
			"name" "npc_dota_hero_juggernaut"
			"label" "juggernaut"
		}
		"2"
{
			"name" "npc_dota_hero_phantom_assassin"
			"label" "phantom_assassin"
		}
		"3"
{
			"name" "npc_dota_hero_sniper"
			"label" "sniper"
		}
		"4"
{
			"name" "npc_dota_hero_riki"
			"label" "riki"
		}
		"5"
{
			"name" "npc_dota_hero_phantom_lancer"
			"label" "phantom_lancer"
		}
	}
	"intelligence"
{
		"1"
{
			"name" "npc_dota_hero_lina"
			"label" "lina"
		}
		"2"
{
			"name" "npc_dota_hero_lion"
			"label" "lion"
		}
		"3"
{
			"name" "npc_dota_hero_crystal_maiden"
			"label" "crystal_maiden"
		}
		"4"
{
			"name" "npc_dota_hero_witch_doctor"
			"label" "witch_doctor"
		}
		"5"
{
			"name" "npc_dota_hero_dazzle"
			"label" "dazzle"
		}
	}
	"universal"
{
		"1"
{
			"name" "npc_dota_hero_marci"
			"label" "marci"
		}
		"2"
{
			"name" "npc_dota_hero_primal_beast"
			"label" "primal_beast"
		}
		"3"
{
			"name" "npc_dota_hero_muerta"
			"label" "muerta"
		}
		"4"
{
			"name" "npc_dota_hero_dawnbreaker"
			"label" "dawnbreaker"
		}
		"5"
{
			"name" "npc_dota_hero_kez"
			"label" "kez"
		}
	}
	"hero_cost" "100"
	"refresh_cost" "20"
	"bench_slot_cost" "200"
	"bench_slot_max" "5"
	"lineup_max" "5"
	"initial_gold" "300"
}
