"items"
{
	"catalog"
{
		"1"
{
			"name" "item_power_treads"
			"cost" "1400"
	}
		"2"
{
			"name" "item_phase_boots"
			"cost" "1500"
	}
		"3"
{
			"name" "item_arcane_boots"
			"cost" "1300"
	}
		"4"
{
			"name" "item_magic_wand"
			"cost" "450"
	}
		"5"
{
			"name" "item_bracer"
			"cost" "520"
	}
		"6"
{
			"name" "item_blink"
			"cost" "2250"
	}
		"7"
{
			"name" "item_black_king_bar"
			"cost" "4175"
	}
		"8"
{
			"name" "item_satanic"
			"cost" "5050"
	}
		"9"
{
			"name" "item_butterfly"
			"cost" "4900"
	}
		"10"
{
			"name" "item_desolator"
			"cost" "3900"
	}
		"11"
{
			"name" "item_heart"
			"cost" "5000"
	}
		"12"
{
			"name" "item_sheepstick"
			"cost" "5475"
	}
		"13"
{
			"name" "item_ultimate_scepter"
			"cost" "4200"
	}
		"14"
{
			"name" "item_aghanims_shard"
			"cost" "1400"
	}
		"15"
{
			"name" "item_pipe"
			"cost" "3475"
	}
		"16"
{
			"name" "item_crimson_guard"
			"cost" "4100"
	}
		"17"
{
			"name" "item_shivas_guard"
			"cost" "4850"
	}
		"18"
{
			"name" "item_lotus_orb"
			"cost" "4125"
	}
		"19"
{
			"name" "item_sphere"
			"cost" "4350"
	}
		"20"
{
			"name" "item_manta"
			"cost" "4500"
	}
		"21"
{
			"name" "item_diffusal_blade"
			"cost" "3100"
	}
		"22"
{
			"name" "item_abyssal_blade"
			"cost" "6125"
	}
		"23"
{
			"name" "item_assault"
			"cost" "5125"
	}
		"24"
{
			"name" "item_radiance"
			"cost" "4900"
	}
		"25"
{
			"name" "item_ethereal_blade"
			"cost" "4700"
	}
		"26"
{
			"name" "item_orchid"
			"cost" "3475"
	}
		"27"
{
			"name" "item_bloodthorn"
			"cost" "6600"
	}
		"28"
{
			"name" "item_nullifier"
			"cost" "4400"
	}
		"29"
{
			"name" "item_silver_edge"
			"cost" "5100"
	}
		"30"
{
			"name" "item_heavens_halberd"
			"cost" "4675"
	}
		"31"
{
			"name" "item_force_staff"
			"cost" "2150"
	}
		"32"
{
			"name" "item_glimmer_cape"
			"cost" "1850"
	}
		"33"
{
			"name" "item_guardian_greaves"
			"cost" "4600"
	}
		"34"
{
			"name" "item_solar_crest"
			"cost" "2625"
	}
		"35"
{
			"name" "item_vladmir"
			"cost" "4175"
	}
		"36"
{
			"name" "item_mask_of_madness"
			"cost" "2175"
	}
		"37"
{
			"name" "item_greater_crit"
			"cost" "5100"
	}
		"38"
{
			"name" "item_overwhelming_blink"
			"cost" "4850"
	}
		"39"
{
			"name" "item_swift_blink"
			"cost" "4750"
	}
		"40"
{
			"name" "item_moon_shard"
			"cost" "3900"
	}
	}
}
