"loot"
{
	"loot_basic"
{
		"name" "野怪关掉落"
		"items"
{
			"1" { "item" "item_magic_wand" "chance" "0.35" }
			"2" { "item" "item_glimmer_cape" "chance" "0.3" }
			"3" { "item" "item_mask_of_madness" "chance" "0.2" }
		}
	}
	"loot_hero"
{
		"name" "英雄关掉落"
		"items"
{
			"1" { "item" "item_desolator" "chance" "0.3" }
			"2" { "item" "item_black_king_bar" "chance" "0.2" }
			"3" { "item" "item_force_staff" "chance" "0.35" }
		}
	}
	"loot_boss"
{
		"name" "Boss 掉落"
		"items"
{
			"1" { "item" "item_black_king_bar" "chance" "0.6" }
			"2" { "item" "item_ultimate_scepter" "chance" "0.5" }
			"3" { "item" "item_sheepstick" "chance" "0.25" }
		}
	}
}
