"""Offline campaign loot catalog. Native items + CURRENT neutral rotation, not shop-only.
All recipe scrolls and Roshan's Banner are excluded by campaign policy.
Self-consuming Shard/Blessing use transferable Roshan consumables instead of
AddItemByName on the commander. Blessing recipe excluded: auto-combination on
commander can consume Scepter without upgrading a roster hero.
"""
import argparse
import hashlib
import importlib.util
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location('native_author', ROOT / 'scripts/author-playable-heroes.py')
native = importlib.util.module_from_spec(spec)
spec.loader.exec_module(native)
DATA = ROOT / 'game/dota_addons/dota2_rpg/scripts/data'
LUA = ROOT / 'game/dota_addons/dota2_rpg/scripts/vscripts/data/campaign_loot_catalog.lua'
SPECIAL = set(('ward_observer cheese famango great_famango greater_famango royale_with_cheese ward_dispenser tango_single ultimate_scepter_roshan aghanims_shard_roshan aegis refresher_shard roshans_banner miniboss_minion_summoner foragers_health foragers_stats foragers_mana').split())
ALIASES = {'item_aghanims_shard': 'item_aghanims_shard_roshan', 'item_ultimate_scepter_2': 'item_ultimate_scepter_roshan'}

def build(items_bytes, neutral_bytes):
    items = native.parse_kv(items_bytes.decode('utf-8-sig'))['DOTAAbilities']
    rotation = native.parse_kv(neutral_bytes.decode('utf-8-sig'))['neutral_items']['neutral_tiers']
    active = set()
    enhancements = set()
    for tier in rotation.values():
        active.update(tier['items'])
        for group in tier['enhancements'].values():
            enhancements.update(group)
    rows = []
    for name, schema in sorted(items.items()):
        if not isinstance(schema, dict):
            continue
        reason, category = None, None
        if name.startswith('item_recipe_') or schema.get('ItemRecipe') == '1':
            reason = 'Campaign policy: no recipe scroll drops'
        elif name == 'item_roshans_banner':
            reason = 'Campaign policy: no Roshan Banner drops'
        elif name == 'item_tpscroll':
            reason = 'Campaign policy: the mode has no Town Portal Scroll'
        elif schema.get('IsObsolete') == '1':
            reason = 'Native IsObsolete=1'
        elif name in active:
            category = 'neutral'
        elif name in enhancements:
            category = 'neutral_enhancement'
        elif schema.get('ItemIsNeutralActiveDrop') == '1' or schema.get('ItemIsNeutralPassiveDrop') == '1':
            reason = 'Not in installed neutral_items.txt current rotation (retired/test/token definition)'
        elif name.removeprefix('item_') in SPECIAL:
            category = 'special'
        elif schema.get('ItemPurchasable', '1') != '0' and int(schema.get('ItemCost', '0')) > 0:
            category = 'standard'
        else:
            short = name.removeprefix('item_')
            if short in ('black_grimoire', 'eldwurms_edda', 'furion_gold_bag', 'grisgris', 'tidehunter_fish'):
                reason = 'Hero-created/bound mechanic; arbitrary commander grant lacks originating hero state'
            elif short in ('courier', 'flying_courier'):
                reason = 'Legacy courier purchase consumable; current standard couriers are automatic'
            elif short == 'madstone_bundle':
                reason = 'Cast-on-pickup neutral crafting currency; campaign awards actual neutral equipment instead'
            else:
                reason = 'Event or test-only definition (Muerta event, mutation, pocket entity or super blink); not standard obtainable equipment'
        rows.append(dict(name=name, category=category, excluded_reason=reason,
                         delivery=ALIASES.get(name, name) if category else None, schema=schema))
    return dict(source_sha256=hashlib.sha256(items_bytes).hexdigest(),
                neutral_sha256=hashlib.sha256(neutral_bytes).hexdigest(),
                policy=__doc__, counts=dict(Counter(r['category'] or 'excluded' for r in rows)), items=rows)


LF = chr(10)  # Real newline; keeps the generated table free of escape noise.

HEADER = [
    '-- Generated by scripts/author-campaign-loot.py; no native creation/precache at startup.',
    '-- neutral = true marks native current-rotation neutral items: the engine keeps them in the',
    '-- dedicated neutral slot (16), outside the 0..14 inventory/backpack/native-stash range.',
    'return {',
]


def row_line(row):
    flag = ', neutral = true' if row['category'] in ('neutral', 'neutral_enhancement') else ''
    return '    { name = "' + row['name'] + '", delivery = "' + row['delivery'] + '"' + flag + ' },'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--vpk', type=Path, default=native.DEFAULT_VPK)
    args = parser.parse_args()
    catalog = build(native.read_entry(args.vpk, 'scripts/npc/items.txt'), native.read_entry(args.vpk, 'scripts/npc/neutral_items.txt'))
    (DATA / 'campaign_loot_catalog.json').write_text(json.dumps(catalog, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')
    pool = [r for r in catalog['items'] if r['category']]
    LUA.write_text(LF.join(HEADER + [row_line(r) for r in pool] + ['}']) + LF, encoding='utf-8')
    print(json.dumps(catalog['counts'], sort_keys=True), 'pool=', len(pool))

if __name__ == '__main__':
    main()
