#!/usr/bin/env python3
"""Generate native card definitions from BASIC_CARDS_V1.md without rewriting prose.

Only table padding is stripped; names, axes, conditions and effects retain the
source wording, punctuation and Markdown emphasis. COST tiers are sample values.
Run with --check to verify the checked-in JavaScript without modifying it.
"""

import argparse
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/BASIC_CARDS_V1.md"
OUTPUT = ROOT / "content/dota_addons/dota2_rpg_endless/panorama/scripts/custom_game/card_forge_data.js"
LUA_OUTPUT = ROOT / "game/dota_addons/dota2_rpg_endless/scripts/vscripts/endless/card_catalog.lua"
FACTIONS = {
    "E": ("element", "lina"),
    "C": ("civilization", "dragon_knight"),
    "D": ("divine", "omniknight"),
    "A": ("abyss", "nevermore"),
    "W": ("wild", "ursa"),
}
TYPES = {"g": ("buff", 9, 6), "c": ("charge", 7, 5), "f": ("field", 4, 4)}
FIELD_CONDITION = "开战生成，覆盖全战场；装备者阵亡 / 复活 / 换人不影响，持续到本场战斗结束"


def read_cards():
    cards = []
    seen = set()
    for number, line in enumerate(SOURCE.read_text(encoding="utf-8").splitlines(), 1):
        if not re.match(r"^\s*\|\s*[ECDAW]-[gcf]\d+\s*\|", line):
            continue
        # E-g3 intentionally lacks a closing pipe in the original document.
        row = line.strip()[1:]
        if row.endswith("|"):
            row = row[:-1]
        cells = [cell.strip() for cell in row.split("|")]
        card_id = cells[0]
        prefix, suffix = card_id.split("-")
        kind = suffix[0]
        card_type, _, columns = TYPES[kind]
        if len(cells) != columns:
            raise ValueError(f"{SOURCE.name}:{number}: {card_id} expects {columns} columns, got {len(cells)}")
        if card_id in seen:
            raise ValueError(f"{SOURCE.name}:{number}: duplicate ID {card_id}")
        seen.add(card_id)
        faction, art = FACTIONS[prefix]
        cards.append({
            "id": card_id,
            "name": cells[1],
            "faction": faction,
            "type": card_type,
            "axis": cells[2],
            "condition": cells[4] if kind == "g" else cells[3] if kind == "c" else FIELD_CONDITION,
            "effect": cells[-1],
            "art": art,
            "copies": 3,
            "level": 3,
            "load": 1,
            "plus": 0,
            "tier": "普通",
        })
    expected = {
        f"{prefix}-{kind}{index}"
        for prefix in FACTIONS
        for kind, (_, count, _) in TYPES.items()
        for index in range(1, count + 1)
    }
    if seen != expected:
        raise ValueError(f"Expected exactly 100 basic cards; missing={sorted(expected - seen)}, unexpected={sorted(seen - expected)}")
    return cards


def render(cards):
    return (
        "// Generated by scripts/build-native-card-data.py from docs/BASIC_CARDS_V1.md.\n"
        "// Source-original Chinese design text; COST tiers are sample values. Do not edit.\n"
        '(function () {\n  "use strict";\n  var cards = '
        + json.dumps(cards, ensure_ascii=False, indent=2)
        + ';\n  if (typeof module !== "undefined" && module.exports) {\n'
        "    module.exports = cards;\n"
        "  } else {\n"
        "    GameUI.CustomUIConfig().CardForgeData = cards;\n"
        "  }\n"
        "})();\n"
    )


def render_lua(cards):
    def value(item):
        if isinstance(item, str):
            return '"' + item.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r') + '"'
        if isinstance(item, (int, float)):
            return str(item)
        return '{' + ','.join('[' + value(k) + ']=' + value(v) for k, v in item.items()) + '}'
    return '-- Generated by scripts/build-native-card-data.py. Source prose, not executable effects.\nreturn {\n' + ',\n'.join('  [' + value(c['id']) + ']=' + value(c) for c in cards) + '\n}\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated JavaScript is missing or stale")
    args = parser.parse_args()
    try:
        cards = read_cards()
        generated = render(cards).encode("utf-8")
        outputs = {OUTPUT: generated, LUA_OUTPUT: render_lua(cards).encode('utf-8')}
        for path, content in outputs.items():
            if args.check:
                if not path.exists() or path.read_text(encoding='utf-8') != content.decode('utf-8'):
                    print(f'Card data missing or stale: {path}; run python scripts/build-native-card-data.py', file=sys.stderr)
                    return 1
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(content)
        print(f'Native and server catalog {"checked" if args.check else "generated"} ({len(cards)} cards).')
    except (OSError, ValueError) as error:
        print(str(error), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
