"""Generate campaign creatures from a compact, extracted native KV snapshot.

Refresh snapshot explicitly with --extract UNITS ABILITIES and optional
--extra-abilities FILE ... for definitions stored in native hero files. Generation
uses only the checked-in snapshot; it never needs a Dota installation.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / 'scripts/data/campaign-neutral-native.json'
OUTPUT = ROOT / 'game/dota_addons/dota2_rpg/scripts/npc/npc_units_custom.txt'
MARKER = '    // BEGIN GENERATED CAMPAIGN NEUTRALS'
# Raise Dead is defined in npc_dota_hero_troll_warlord.txt and creates this unit.
ALIASES = {'npc_dota_neutral_hellbear_smasher': 'npc_dota_neutral_polar_furbolg_ursa_warrior'}
SUMMONS = {'dark_troll_warlord_raise_dead': ['npc_dota_dark_troll_warlord_skeleton_warrior']}


def parse_kv(text):
    tokens = re.findall(r'"(?:\\.|[^"\\])*"|//[^\n]*|[{}]|[^\s{}"]+', text)
    tokens = iter(t for t in tokens if not t.startswith('//'))

    def block(nested=False):
        result = {}
        for token in tokens:
            if token == '}':
                if not nested:
                    raise ValueError('Unexpected closing brace')
                return result
            key = token[1:-1] if token.startswith('"') else token
            value = next(tokens)
            result[key] = block(True) if value == '{' else value[1:-1] if value.startswith('"') else value
        if nested:
            raise ValueError('Unclosed KV block')
        return result
    return block()


def campaign_names():
    paths = list((ROOT / 'game/dota_addons/dota2_rpg/scripts/data').glob('levels*'))
    paths.append(ROOT / 'scripts/author-enemy-roster.py')
    return sorted({name for path in paths if path.is_file()
                   for name in re.findall(r'npc_dota_neutral_[a-z0-9_]+', path.read_text(encoding='utf-8'))})


def extract(units_path, abilities_path, extra_abilities=()):
    units = parse_kv(Path(units_path).read_text(encoding='utf-8-sig'))['DOTAUnits']
    abilities = parse_kv(Path(abilities_path).read_text(encoding='utf-8-sig'))['DOTAAbilities']
    for extra in extra_abilities:
        abilities.update(parse_kv(Path(extra).read_text(encoding='utf-8-sig'))['DOTAAbilities'])
    selected = {}
    contracts = {}
    pending = campaign_names()
    while pending:
        name = pending.pop(0)
        if name in selected:
            continue
        selected[name] = units[ALIASES.get(name, name)]
        for key, ability in selected[name].items():
            if re.fullmatch(r'Ability\d+', key) and ability:
                contracts[ability] = abilities.get(ability)
                # Preserve unresolved engine abilities without inventing KV.
                pending.extend(SUMMONS.get(ability, []))
    snapshot = {
        'provenance': 'Extracted installed Dota npc_units.txt, npc_abilities.txt and supplemental hero ability files; only campaign units, their summon dependencies and ability contracts.',
        'source_sha256': {
            'npc_units.txt': hashlib.sha256(Path(units_path).read_bytes()).hexdigest(),
            'npc_abilities.txt': hashlib.sha256(Path(abilities_path).read_bytes()).hexdigest(),
            **{Path(path).name: hashlib.sha256(Path(path).read_bytes()).hexdigest()
               for path in extra_abilities},
        },
        'aliases': ALIASES,
        'unresolved_abilities': sorted(name for name, data in contracts.items() if data is None),
        'summons': SUMMONS,
        'units': dict(sorted(selected.items())),
        'abilities': dict(sorted(contracts.items())),
    }
    SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)
    SNAPSHOT.write_text(json.dumps(snapshot, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')


def creature(native):
    # CreateUnitByName supplies the battle team. Omit native camp identity.
    return {key: 'npc_dota_creature' if key == 'BaseClass' else value
            for key, value in native.items() if key not in ('TeamName', 'IsNeutralUnitType')}


def render_block(name, fields, indent=4):
    pad = ' ' * indent
    lines = [f'{pad}"{name}"', pad + '{']
    for key, value in fields.items():
        if isinstance(value, dict):
            lines.extend(render_block(key, value, indent + 4))
        else:
            lines.append(f'{pad}    "{key}"'.ljust(indent + 36) + f'"{value}"')
    return lines + [pad + '}']


def generated(snapshot):
    lines = [MARKER,
             '    // Generated by scripts/build-campaign-neutral-units.py; native snapshot in scripts/data.',
             '    // Creature base permits scripted orders without neutral camp AI.',
             '    // Preserve native ability slots (including passive neutral_upgrade), stats and visuals.',
             '    // Legacy hellbear_smasher uses native polar_furbolg_ursa_warrior fields.',
             '    // Only BaseClass changes; TeamName and IsNeutralUnitType are omitted.', '']
    for name, native in snapshot['units'].items():
        lines.extend(render_block(name, creature(native)))
        lines.append('')
    return '\n'.join(lines) + '}\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--extract', nargs=2, metavar=('UNITS', 'ABILITIES'))
    parser.add_argument('--extra-abilities', nargs='*', default=[])
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    if args.extract:
        extract(*args.extract, extra_abilities=args.extra_abilities)
    snapshot = json.loads(SNAPSHOT.read_text(encoding='utf-8'))
    missing = set(campaign_names()) - snapshot['units'].keys()
    if missing:
        raise ValueError(f'Native snapshot missing campaign units: {sorted(missing)}')
    current = OUTPUT.read_text(encoding='utf-8')
    # Preserve the existing sandbox block verbatim during the first migration.
    prefix = current.split(MARKER)[0] if MARKER in current else current.split('    //----------------------------------------------------------------------')[0]
    updated = prefix + generated(snapshot)
    if args.check:
        if current != updated:
            raise SystemExit('Campaign neutral definitions need regeneration')
    else:
        OUTPUT.write_text(updated, encoding='utf-8', newline='\n')
    print(f'Verified {len(campaign_names())} campaign neutral types; {len(snapshot["units"])} creature definitions.')


if __name__ == '__main__':
    main()
