"""Generate native neutral recruitment aliases and a Lua choice catalog.

Refresh with --extract UNITS ITEMS. Ordinary generation and --check use the
checked-in evidence snapshot; no network or Dota installation is required.
Aliases preserve native neutral identity, unlike campaign creature overrides.
"""
import argparse
import hashlib
import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location('campaign_kv', ROOT / 'scripts/build-campaign-neutral-units.py')
kv = importlib.util.module_from_spec(spec)
spec.loader.exec_module(kv)
SNAPSHOT = ROOT / 'scripts/data/neutral-recruitment-native.json'
NPC = ROOT / 'game/dota_addons/dota2_rpg/scripts/npc/npc_units_neutral_recruitment.txt'
LUA = ROOT / 'game/dota_addons/dota2_rpg/scripts/vscripts/battle/neutral_recruitment_catalog.lua'
EXCLUDED = {'npc_dota_neutral_default', 'npc_dota_neutral_mud_golem_split', 'npc_dota_neutral_mud_golem_split_doom'}


def extract(units_path, items_path):
    raw_units, raw_items = Path(units_path).read_bytes(), Path(items_path).read_bytes()
    units = kv.parse_kv(raw_units.decode('utf-8-sig'))['DOTAUnits']
    items = kv.parse_kv(raw_items.decode('utf-8-sig'))['DOTAAbilities']
    selected = {name: data for name, data in sorted(units.items())
                if name.startswith('npc_dota_neutral_') and name not in EXCLUDED
                and data.get('BaseClass') == 'npc_dota_creep_neutral'}
    snapshot = {'provenance': 'Native npc_units.txt (dotabuff/d2vpkr upstream); native items.txt fetched via GitHub contents API. Full definitions retained; split summons and default template excluded. Hero limits use live special values, with contracts in data/native_skill_conditions.json.',
                'source_sha256': {'npc_units.txt': hashlib.sha256(raw_units).hexdigest(), 'items.txt': hashlib.sha256(raw_items).hexdigest()},
                'units': selected,
                'items': {name: items[name] for name in ('item_helm_of_the_dominator', 'item_helm_of_the_overlord')}}
    SNAPSHOT.write_text(json.dumps(snapshot, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')


def generate(snapshot):
    npc = ['// Generated by scripts/build-neutral-recruitment.py; preserve native neutral class and flags.', '"DOTAUnits"', '{']
    lua = ['-- Generated by scripts/build-neutral-recruitment.py; native evidence in scripts/data.', 'return {']
    for name, fields in snapshot['units'].items():
        alias = 'npc_rpg_recruit_' + name.removeprefix('npc_dota_neutral_')
        native = dict(fields)
        # Generated candidates cannot grant free kill/conversion farm. This is
        # the sole stat override; conversion itself remains the original spell.
        native.update({'BountyGoldMin': '0', 'BountyGoldMax': '0', 'BountyXP': '0'})
        npc.extend(kv.render_block(alias, native))
        lua.append('    {unit_name="%s", spawn_name="%s", level=%d, ancient=%s},' %
                   (name, alias, int(fields['Level']), 'true' if fields.get('IsAncient') == '1' else 'false'))
    return '\n'.join(npc + ['}', '']), '\n'.join(lua + ['}', ''])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--extract', nargs=2, metavar=('UNITS', 'ITEMS'))
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    if args.extract:
        extract(*args.extract)
    snapshot = json.loads(SNAPSHOT.read_text(encoding='utf-8'))
    for path, text in zip((NPC, LUA), generate(snapshot)):
        if args.check:
            if path.read_text(encoding='utf-8') != text:
                raise SystemExit(f'{path.name} needs regeneration')
        else:
            path.write_text(text, encoding='utf-8', newline='\n')
    print(f'Verified {len(snapshot["units"])} native recruitment choices.')


if __name__ == '__main__':
    main()
