"""Generate expression-support metadata from the bundled native snapshot.
Run with --check in CI. This does not certify native execution.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'game/dota_addons/dota2_rpg/scripts/vscripts/tactics/ability_profiles.lua'


def lua(value):
    if value is None:
        return 'nil'
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=True)
    if isinstance(value, list):
        return '{' + ','.join(lua(item) for item in value) + '}'
    return '{' + ','.join('[' + lua(key) + ']=' + lua(item)
                         for key, item in sorted(value.items())) + '}'


def build():
    data = json.loads((ROOT / 'data/native_skill_conditions.json').read_text(encoding='utf-8'))
    rows = {}
    for row in data['rows']:
        if not row['active']:
            continue
        native = row['native']
        rows[row['id']] = {
            'supported_expression': row['expression_covered'],
            'family': row['family'] or '',
            'snapshot_flags': native['behavior_flags'],
            'source_path': native['source_path'],
        }
    text = '-- Generated by scripts/build-ability-capabilities.py; do not hand edit.\nreturn {\n'
    text += ''.join('    [' + lua(key) + ']=' + lua(value) + ',\n'
                    for key, value in sorted(rows.items())) + '}\n'
    return text, rows


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text, rows = build()
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding='utf-8') != text:
            raise SystemExit('ability_profiles.lua is stale')
    else:
        OUT.write_text(text, encoding='utf-8')
    print('profiles=%d expression_supported=%d' % (
        len(rows), sum(row['supported_expression'] for row in rows.values())))
